### ISSUE TITLE
yammer bloqué par proxy pro

### ISSUE THREAD

**Issue by RLesur** [SSP-Lab/Hackathon-2018#1]
Bonjour,

Pour information, `yammer` est bloqué par mon proxy professionnel.
Je ne sais pas si je suis le seul dans ce cas.
Le choix de `yammer` est-il définitif ou bien d'autres solutions (`slack` par ex.) sont-elles envisageables ?

Cordialement,

Romain Lesur

**Comment by benjisaka** [comment]
Bonjour Romain,

de notre côté c'est Slack qui est bloqué par le proxy !
N'hésite pas à nous contacter à info-hackathon@insee.fr si tu as des questions.
Nous mettrons toutes les ressources sur ce repo Github dans tous les cas.

A bientôt !

Benjamin

**Comment by RLesur** [comment]
Bonjour Benjamin,

Ah, je vois ! Il ne reste plus qu'à croiser les doigts pour que personne n'ait l'idée de bloquer GitHub.

A bientôt,

Romain
